## Course Assignment Instructions
You should have Python (version 3.8 or later) and Jupyter Notebook installed to complete this assignment. You will write code in the empty cell/cells below the problem. While most of this will be a programming assignment, some questions will ask you to "write a few sentences" in markdown cells. 

Submission Instructions:

Create a labs directory in your personal class repository (e.g., located in your home directory)
Clone the class repository
Copy this Jupyter notebook file (.ipynb) into your repo/labs directory
Make your edits, commit changes, and push to your repository
All submissions must be pushed before the due date to avoid late penalties

* Install the numpy, scipy, statsmodels, and pandas packages (we will be using these throughout the semester)

In [1]:
pip install numpy scipy statsmodels pandas

Note: you may need to restart the kernel to use updated packages.


* Print out the numerical constant pi with ten digits after the decimal point using constant 'pi'. You will need to use the math module in python for this. 

In [188]:
import math

print(round(math.pi,10))

3.1415926536


* Sum up the first 103 terms of the series 1 + 1/2 + 1/4 + 1/8 + ... use base python

In [190]:
sum = 0

for num in range(0, 103):
    sum += (0.5 ** num)

print(sum)

2.0


using numpy

In [1]:
import numpy as np

total = np.sum(1/(2 ** i) for i in np.arange(103))
print(total)

inf


C:\Users\Jacob\AppData\Local\Temp\ipykernel_7932\2937037569.py:3: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  total = np.sum(1/(2 ** i) for i in np.arange(103))
C:\Users\Jacob\AppData\Local\Temp\ipykernel_7932\2937037569.py:3: RuntimeWarning: divide by zero encountered in scalar divide
  total = np.sum(1/(2 ** i) for i in np.arange(103))


 * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.  * The issue here arises because NumPy's 2 ** np.arange(103) may overflow for very large exponents, leading to incorrect results. NumPy uses fixed-precision data types, which can cause problems when dealing with extremely large numbers.

In [5]:
total = np.sum(1/(2.0 ** i) for i in np.arange(103))
print(total)

2.0


C:\Users\Jacob\AppData\Local\Temp\ipykernel_15796\326380725.py:1: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  total = np.sum(1/(2.0 ** i) for i in np.arange(103))


* Find the product of the first 387 terms of `1 * 1/2 * 1/4 * 1/8 *` ...

using base python

In [196]:
prod = 1

for num in range(387):
    prod *= 1/(2 ** num)

print(prod)

0.0


using numpy

In [198]:
num = np.prod(1/(2.0 ** np.arange(387)))
print(num)

0.0


Is this answer *exactly* correct?

No, this answer is not exactly correct. The number should be positive although very small and the answer generated is a result of numerical underflow.

* Figure out a means to express the answer more exactly. Not compute exactly, but express more exactly.

In [7]:
import math as m

total = -m.log(2) * sum(range(387))
print(total)

-51771.856063202875


* using numpy ... Hint: use the `log` and `sum` functions in numpy

In [208]:
total = -np.log(2) * np.sum(np.arange(387))
print(total)

-51771.856063202875


* Create the sequence `x = [Inf, 20, 18, ..., -20]`.

Pure python

In [210]:
# Create the sequence
x = [float('inf')] + list(range(20, -21, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


Using numpy

In [212]:
# Create the sequence
x = [float('inf')] + list(np.arange(20, -22, -2))

# Print the result
print(x)

[inf, 20, 18, 16, 14, 12, 10, 8, 6, 4, 2, 0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20]


*   Create the sequence `x = [log_3(Inf), log_3(100), log_3(98), ... log_3(-20)]` ... Use `log` from numpy.

In [214]:
x = np.log([float('inf')] + list(np.arange(100, -21, -2)))/np.log(3)

print(x)

[       inf 4.19180655 4.17341725 4.15464877 4.13548513 4.11590934
 4.09590327 4.0754476  4.05452164 4.03310326 4.01116872 3.98869254
 3.96564727 3.94200337 3.91772888 3.89278926 3.86714702 3.84076143
 3.81358809 3.78557852 3.75667961 3.72683303 3.69597451 3.66403301
 3.63092975 3.59657703 3.5608768  3.52371901 3.48497958 3.44451785
 3.4021735  3.35776278 3.31107361 3.26185951 3.20983168 3.15464877
 3.09590327 3.03310326 2.96564727 2.89278926 2.81358809 2.72683303
 2.63092975 2.52371901 2.4021735  2.26185951 2.09590327 1.89278926
 1.63092975 1.26185951 0.63092975       -inf        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan]


C:\Users\Jacob\AppData\Local\Temp\ipykernel_8516\1696641289.py:1: RuntimeWarning: divide by zero encountered in log
  x = np.log([float('inf')] + list(np.arange(100, -21, -2)))/np.log(3)
C:\Users\Jacob\AppData\Local\Temp\ipykernel_8516\1696641289.py:1: RuntimeWarning: invalid value encountered in log
  x = np.log([float('inf')] + list(np.arange(100, -21, -2)))/np.log(3)


* Create a vector of booleans where the entry is true if `x[i]` is positive and finite. Use `&` from base python along with `isnan` and `isinfinite` from numpy

In [252]:
y = ~np.isnan(x) & np.isfinite(x) & (x > 0)

print(y)

[False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True False False False False False False False False False
 False False]


* Locate the indices of the non-real numbers in this vector. Numpy has a `where` function in lieu of R's `which`

In [256]:
f_indices = np.where(y == False)[0]

print(f_indices)

[ 0 51 52 53 54 55 56 57 58 59 60 61]


* Locate the indices of the infinite quantities in this vector using `where` and `isinf` from numpy.

In [268]:
print(np.where(np.isinf(x))[0])

[ 0 51]


* Locate the indices of the min and max in this vector. Hint: use the `arg.min` and `arg.max` functions from numpy

In [270]:
xs = [i for i in x if (~np.isnan(i))]
#print(xs)
r = [np.argmax(xs), np.argmin(xs)]

print(r)

[0, 51]


* Count the number of unique values in `x`. Use `unique` from numpy.

In [56]:
print(np.unique(x).size)

53


* Cast `x` to a factor. Do the number of levels make sense? Should be 53 unique values. Use `categorical` from pandas.

In [65]:
import pandas as pd

# Cast x to a categorical (similar to as.factor(x) in R)
x_factor = pd.Categorical(x)

# Check the unique levels (categories)
levels = x_factor.categories
num_levels = len(levels)

print(f"Factor levels: {levels}")
print(f"Number of levels: {num_levels}")

Factor levels: Index([              -inf, 0.6309297535714574, 1.2618595071429148,
       1.6309297535714573,  1.892789260714372,  2.095903274289385,
       2.2618595071429146,  2.402173502732879, 2.5237190142858297,
        2.630929753571457, 2.7268330278608417, 2.8135880922155954,
       2.8927892607143724,   2.96564727304425,  3.033103256304337,
       3.0959032742893844,  3.154648767857287, 3.2098316767340234,
       3.2618595071429146, 3.3110736128178324,  3.357762781432299,
       3.4021735027328797, 3.4445178457870527, 3.4849795837717283,
       3.5237190142858297, 3.5608767950073115, 3.5965770266157073,
       3.6309297535714573, 3.6640330098757947, 3.6959745056821194,
       3.7268330278608417,  3.756679610828472,  3.785578521428744,
        3.813588092215595, 3.8407614303054807, 3.8671470234508067,
        3.892789260714372, 3.9177288817897304, 3.9420033663892897,
       3.9656472730442496, 3.9886925350037563,  4.011168719591413,
       4.0331032563043365, 4.0545216380691365, 

* In Python, using pandas, NaN is not treated as a level in a categorical type by default. Pandas does not allow NaN to be a category. To include NaN as a level, you need to explicitly handle it by filling them with a placeholder value (like "NaN" or a specific number) before making the data categorical. Use `categorical` and `isna` from pandas.

In [67]:
# Replace NaN with a placeholder value (e.g., 'NaN')
x_filled = [val if not pd.isna(val) else 'NaN' for val in x]

# Convert to categorical
x_factor = pd.Categorical(x_filled)

# Check the unique levels (including 'NaN' as a level)
factor_levels = x_factor.categories
num_levels = len(factor_levels)

print(f"Factor levels (including NaN): {factor_levels}")
print(f"Number of levels: {num_levels}")

Factor levels (including NaN): Index([              -inf, 0.6309297535714574, 1.2618595071429148,
       1.6309297535714573,  1.892789260714372,  2.095903274289385,
       2.2618595071429146,  2.402173502732879, 2.5237190142858297,
        2.630929753571457, 2.7268330278608417, 2.8135880922155954,
       2.8927892607143724,   2.96564727304425,  3.033103256304337,
       3.0959032742893844,  3.154648767857287, 3.2098316767340234,
       3.2618595071429146, 3.3110736128178324,  3.357762781432299,
       3.4021735027328797, 3.4445178457870527, 3.4849795837717283,
       3.5237190142858297, 3.5608767950073115, 3.5965770266157073,
       3.6309297535714573, 3.6640330098757947, 3.6959745056821194,
       3.7268330278608417,  3.756679610828472,  3.785578521428744,
        3.813588092215595, 3.8407614303054807, 3.8671470234508067,
        3.892789260714372, 3.9177288817897304, 3.9420033663892897,
       3.9656472730442496, 3.9886925350037563,  4.011168719591413,
       4.0331032563043365, 4.05

* Cast `x` to integers. Use `where`, `isinfinite` from numpy and `astype` from base python.

In [272]:
x_int = [val.astype(int) for val in x if (np.isfinite(val))]

print(x_int)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 0]


* Use `x` to create a new vector `y` containing only the real numbers in x. Use `isnan`, `logical_and`, and `reduce` from numpy

In [280]:
y = [val for val in x if np.logical_and(~np.isnan(val), ~np.isinf(val))]
print(y)

y = x[np.logical_and.reduce((~np.isnan(x), np.isfinite(x), x > 0))]
print(y)

[4.19180654857877, 4.173417251894302, 4.154648767857287, 4.135485128951194, 4.115909337343186, 4.095903274289384, 4.07544759935851, 4.0545216380691365, 4.0331032563043365, 4.011168719591413, 3.9886925350037563, 3.9656472730442496, 3.9420033663892897, 3.9177288817897304, 3.892789260714372, 3.8671470234508067, 3.8407614303054807, 3.813588092215595, 3.785578521428744, 3.756679610828472, 3.7268330278608417, 3.6959745056821194, 3.6640330098757947, 3.6309297535714573, 3.5965770266157073, 3.5608767950073115, 3.5237190142858297, 3.4849795837717283, 3.4445178457870527, 3.4021735027328797, 3.357762781432299, 3.3110736128178324, 3.2618595071429146, 3.2098316767340234, 3.154648767857287, 3.0959032742893844, 3.033103256304337, 2.96564727304425, 2.8927892607143724, 2.8135880922155954, 2.7268330278608417, 2.630929753571457, 2.5237190142858297, 2.402173502732879, 2.2618595071429146, 2.095903274289385, 1.892789260714372, 1.6309297535714573, 1.2618595071429148, 0.6309297535714574]
[4.19180655 4.17341725

* Use the left rectangle method to numerically integrate x^2 from 0 to 1 with rectangle width size 1e-6. Use `arrange` and `sum` from numpy

In [92]:
# Define the rectangle width
width = 1e-6

# Create the sequence for the left endpoints (similar to seq in R)
x = np.arange(0, 1, width)

# Compute the sum using the left rectangle method
approximation = np.sum(x ** 2) * width

# Print the result
print(approximation)


0.33333283333349994


* Calculate the average of 100 realizations of standard Bernoullis in one line using the numpy's random.choice function.

In [284]:
np.mean(np.random.choice([0,1], size = 100, replace = True))

0.46

* Calculate the average of 500 realizations of Bernoullis with p = 0.9 in one line using the `random.choice` and `mean` functions in numpy.

In [134]:
np.mean(np.random.choice([0,1], size = 500, replace = True, p = [.1,.9]))

0.91

* Calculate the average of 1000 realizations of Bernoullis with p = 0.9 in one line using `binom` from scipy.stats.

In [302]:
from scipy.stats import binom

av_bern = binom.rvs(n = 1, p = 0.9, size = 1000).mean()
print(av_bern)

0.912


* Let `n = 50`. Create a n x n matrix `R` of exactly 50% entries 0's, 25% 1's 25% 2's. These values should be in random locations.

In [17]:
import pandas as pd

# Set n
n = 50

# Generate the random values with specified proportions
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)
# Reshape the values into an n x n matrix
R = values.reshape(n, n)

# Convert the matrix into a DataFrame
df = pd.DataFrame(R)

# Print the DataFrame
print(df)

    0   1   2   3   4   5   6   7   8   9   ...  40  41  42  43  44  45  46  \
0    0   0   0   1   0   0   2   1   0   1  ...   0   1   0   0   2   0   0   
1    1   0   0   1   0   0   2   2   0   0  ...   2   0   1   2   2   0   2   
2    0   0   2   0   2   0   0   2   1   1  ...   2   2   1   1   0   1   0   
3    0   0   0   0   0   2   0   0   0   1  ...   0   2   2   2   0   0   0   
4    0   2   1   0   0   1   1   2   1   1  ...   1   2   1   0   0   1   1   
5    0   2   2   0   0   0   0   1   0   2  ...   2   1   0   1   1   0   0   
6    2   1   0   1   0   1   0   0   1   1  ...   0   2   0   0   1   0   2   
7    1   0   1   2   2   0   0   0   0   1  ...   1   1   0   0   0   0   2   
8    2   2   0   1   1   0   1   0   2   1  ...   2   2   1   0   2   0   1   
9    0   1   0   2   1   0   0   0   1   1  ...   0   1   0   0   2   0   0   
10   0   1   1   2   2   1   1   0   1   1  ...   2   2   2   2   0   2   1   
11   1   1   0   2   1   1   0   0   2   0  ...   0 

* Randomly punch holes (i.e. `NA`) values in this matrix so that an each entry is missing with probability 30%.

In [310]:
# Convert to float to allow NaN
df = df.astype(float)

# Randomly punch holes with 30% probability
mask = np.random.choice([True, False], size=df.shape, p=[0.3, 0.7])
df[mask] = np.nan

# View the resulting DataFrame
print(df)

     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   2.0  2.0  NaN  1.0  0.0  NaN  0.0  0.0  0.0  NaN  ...  0.0  NaN  2.0  0.0   
1   0.0  NaN  NaN  2.0  0.0  1.0  2.0  NaN  1.0  2.0  ...  0.0  0.0  0.0  1.0   
2   NaN  0.0  NaN  2.0  NaN  NaN  1.0  0.0  NaN  NaN  ...  NaN  2.0  1.0  1.0   
3   0.0  NaN  0.0  2.0  1.0  0.0  NaN  0.0  NaN  NaN  ...  2.0  1.0  0.0  0.0   
4   0.0  2.0  2.0  NaN  0.0  2.0  NaN  NaN  NaN  0.0  ...  1.0  0.0  0.0  NaN   
5   NaN  NaN  0.0  1.0  NaN  NaN  NaN  0.0  0.0  NaN  ...  0.0  1.0  0.0  2.0   
6   0.0  NaN  NaN  NaN  NaN  NaN  0.0  NaN  2.0  0.0  ...  0.0  0.0  1.0  NaN   
7   0.0  0.0  1.0  0.0  NaN  1.0  1.0  1.0  NaN  NaN  ...  0.0  1.0  2.0  0.0   
8   1.0  NaN  0.0  2.0  NaN  NaN  0.0  1.0  0.0  0.0  ...  0.0  1.0  NaN  NaN   
9   0.0  0.0  1.0  1.0  0.0  NaN  0.0  1.0  NaN  0.0  ...  2.0  0.0  NaN  0.0   
10  NaN  NaN  NaN  1.0  NaN  1.0  0.0  0.0  2.0  1.0  ...  0.0  NaN  0.0  0.0   
11  0.0  NaN  0.0  NaN  1.0 

In [35]:
import numpy as np
import pandas as pd

# Set matrix dimensions and proportions
n = 50
values = np.random.permutation(
    np.concatenate([
        np.full(int(n * n * 0.5), 0),  # 50% 0's
        np.full(int(n * n * 0.25), 1), # 25% 1's
        np.full(int(n * n * 0.25), 2)  # 25% 2's
    ])
)

# Reshape the matrix
R = values.reshape(n, n)

# Create a mask for punching holes with a 30% probability
random_holes = np.random.choice([True, False], size=(n, n), p=[0.3, 0.7])

# Assign NaN to the corresponding positions
R = R.astype(float)  # Convert to float to support NaN
R[random_holes] = np.nan

# Convert to DataFrame
df = pd.DataFrame(R)


print(df)


     0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0   0.0  2.0  1.0  NaN  1.0  0.0  1.0  NaN  NaN  2.0  ...  NaN  1.0  0.0  2.0   
1   1.0  NaN  NaN  NaN  0.0  0.0  NaN  0.0  1.0  0.0  ...  2.0  0.0  NaN  0.0   
2   1.0  0.0  0.0  NaN  0.0  1.0  0.0  NaN  1.0  0.0  ...  NaN  0.0  NaN  2.0   
3   1.0  0.0  0.0  0.0  NaN  NaN  0.0  2.0  NaN  2.0  ...  0.0  NaN  0.0  NaN   
4   2.0  0.0  NaN  NaN  NaN  NaN  0.0  0.0  1.0  0.0  ...  NaN  0.0  1.0  1.0   
5   0.0  2.0  1.0  2.0  0.0  1.0  NaN  0.0  NaN  0.0  ...  1.0  2.0  0.0  1.0   
6   1.0  0.0  NaN  0.0  0.0  NaN  0.0  2.0  2.0  0.0  ...  0.0  2.0  1.0  1.0   
7   NaN  2.0  NaN  NaN  2.0  0.0  2.0  NaN  NaN  2.0  ...  1.0  0.0  NaN  NaN   
8   0.0  0.0  1.0  NaN  2.0  NaN  2.0  0.0  0.0  NaN  ...  NaN  0.0  2.0  NaN   
9   0.0  1.0  0.0  1.0  NaN  0.0  2.0  1.0  0.0  NaN  ...  1.0  NaN  1.0  1.0   
10  NaN  NaN  1.0  1.0  1.0  0.0  0.0  0.0  1.0  2.0  ...  1.0  0.0  0.0  0.0   
11  0.0  0.0  0.0  NaN  1.0 

* Sort the rows in matrix `R` by the largest row sum to lowest. Be careful about the NA's!

In [9]:
#compute row sums, ignoring nan values

row_sum = np.nansum(R, axis = 1)
#print(row_sum)

#get the row indices sorted by largest row sum to smallest
row_sorted = np.argsort(-row_sum)
print(row_sorted)

[12 17 46 28 14  5  9 49 36 47 19 40 41 37 32 30 16 18 39 42 23 24 44 34
 22  6  7  8 11 31  0 35 33 26  2 27 38  3 10 20 15 25  4  1 48 13 21 43
 45 29]


* Python does not have an apply function. Instead use the nanstd function in numpy to calculate the standard devation of each column. Print them and combine then into a dataframe.

In [11]:
#compute row wise and columb wise that standard deviation

row_sd = np.nanstd(R, axis = 1)
col_sd = np.nanstd(R, axis = 0)

#combine the results into a dictionary

result = {"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()}

print(result["row_sd"])
print(result["col_sd"])

[0.7772268862134539, 0.7323470351758078, 0.7817359599705717, 0.7907630001770314, 0.7310507928372617, 0.9040262963743211, 0.8439143072757395, 0.8156132131683558, 0.8475655413823614, 0.8022459821756386, 0.7680128579652817, 0.8475655413823614, 0.8620067027323833, 0.8142441722754183, 0.8119604537127112, 0.7181259597614283, 0.8559031717046193, 0.8710403975109247, 0.8188787787861144, 0.9131223741405675, 0.8076779989575054, 0.7284313590846835, 0.8198880662670216, 0.8331955809010617, 0.8324100998873475, 0.7634508123364221, 0.75, 0.7941176470588236, 0.9524870371192485, 0.6845227743263395, 0.81967981553775, 0.739985036788772, 0.855235974119758, 0.7908513752537735, 0.8339053308400819, 0.74535599249993, 0.8511022265274601, 0.8359957469322967, 0.7561741254224965, 0.7870038119348597, 0.7752936520529369, 0.8103306747674901, 0.8332682266233364, 0.7082096258096823, 0.8764508485736082, 0.7742615635934225, 0.8569883696666745, 0.8660254037844386, 0.7426364150465379, 0.8177316926151673]
[0.8670237042931574

* combine the results from the previous cell into a dataframe

In [13]:
sd_df = pd.DataFrame({"row_sd": row_sd.tolist(), "col_sd": col_sd.tolist()})
sd_df

row_sd    col_sd
0   0.777227  0.867024
1   0.732347  0.852941
2   0.781736  0.695971
3   0.790763  0.823529
4   0.731051  0.927025
5   0.904026  0.693375
6   0.843914  0.856780
7   0.815613  0.939061
8   0.847566  0.829156
9   0.802246  0.767793
10  0.768013  0.798197
11  0.847566  0.779678
12  0.862007  0.775191
13  0.814244  0.864865
14  0.811960  0.700000
15  0.718126  0.793509
16  0.855903  0.794949
17  0.871040  0.899827
18  0.818879  0.881671
19  0.913122  0.718022
20  0.807678  0.831479
21  0.728431  0.739985
22  0.819888  0.763391
23  0.833196  0.642824
24  0.832410  0.819888
25  0.763451  0.873678
26  0.750000  0.726184
27  0.794118  0.827586
28  0.952487  0.749656
29  0.684523  0.805086
30  0.819680  0.770383
31  0.739985  0.863767
32  0.855236  0.705337
33  0.790851  0.875074
34  0.833905  0.899827
35  0.745356  0.879883
36  0.851102  0.727223
37  0.835996  0.931097
38  0.756174  0.701566
39  0.787004  0.812956
40  0.775294  0.777731
41  0.810331  0.826556
42  0.833268  0.729285
43  0.708210  0.797148
44  0.876451  0.821678
45  0.774262  0.843914
46  0.856988  0.810140
47  0.866025  0.784545
48  0.742636  0.769840
49  0.817732  0.775294

* Use the Pandas apply function to compute a vector whose entries are the count of entries that are 1 or 2 in each column

In [53]:
print(df.fillna(0).apply(np.count_nonzero, axis = 0))
#print(df[df.columns[23]])

0     21
1     16
2     17
3     15
4     24
5     16
6     20
7     19
8     20
9     15
10    18
11    15
12    14
13    13
14    14
15    17
16    17
17    15
18    19
19    17
20    23
21    14
22    15
23    14
24    25
25    17
26    17
27    14
28    18
29    22
30    17
31    20
32    20
33    21
34    16
35    14
36    10
37    18
38    20
39    15
40    20
41    19
42    17
43    14
44    25
45    14
46    18
47    19
48    21
49    22
dtype: int64


Since we just switched between Pandas dataframes and Numpy arrays. Here are some handy ways to check to see if you are working with a Pandas dataframe or a Numpy array

In [109]:
# Check type directly
if type(R) == pd.DataFrame:
    print("R is a Pandas DataFrame")

if type(R) == np.ndarray:
    print("R is a NumPy array")

R is a NumPy array


In [111]:
# isinstance(object, classinfo): This function checks if an object is an instance of a specified class or subclass.
# function utilizing this function to check
def check_type(R):
    if isinstance(R, pd.DataFrame):
        return "Pandas DataFrame"
    elif isinstance(R, np.ndarray):
        return "NumPy array"
    else:
        return "Unknown type"

# Test the function
print(check_type(R))  # Output: Pandas DataFrame

NumPy array


* Create a list whose keys are the column number and values are the vector of the columns.

In [75]:
#key_list = {i : df[df.columns[i]] for i in range(0, 50)}
#print(key_list)
key_list = {i: df[col] for i, col in enumerate(df.columns)}
print(key_list[1])

0     2.0
1     NaN
2     0.0
3     0.0
4     0.0
5     2.0
6     0.0
7     2.0
8     0.0
9     1.0
10    NaN
11    0.0
12    NaN
13    0.0
14    NaN
15    0.0
16    0.0
17    2.0
18    NaN
19    2.0
20    NaN
21    NaN
22    2.0
23    NaN
24    0.0
25    NaN
26    2.0
27    0.0
28    0.0
29    1.0
30    2.0
31    NaN
32    NaN
33    NaN
34    NaN
35    1.0
36    0.0
37    2.0
38    2.0
39    0.0
40    1.0
41    0.0
42    NaN
43    NaN
44    0.0
45    NaN
46    0.0
47    0.0
48    2.0
49    2.0
Name: 1, dtype: float64


* Create a list whose keys are the column number and values are themselves a list with keys: "min" whose value is the minimum of the column, "max" whose value is the maximum of the column, "pct_missing" is the proportion of missingness in the column and "first_NA" whose value is the row number of the first time the NA appears. In R this was accomplished using lappy. In Python we will use dictionary comprehension in tandem with Numpy and Pandas operations.

In [77]:
sp_list = {i : {'min' : df[col][np.argmin(df[col].fillna(3))], 
               'max' : df[col][np.argmax(df[col].fillna(-1))], 
               'pct_missing' : np.mean(np.isnan(df[col])), 
               'first_NA' : np.where(np.isnan(df[col]))[0][0]} for i,col in enumerate(df.columns)}

sp_df = pd.DataFrame(sp_list)
print(sp_df)

              0     1     2     3     4    5    6     7     8     9   ...  \
min          0.0  0.00  0.00  0.00  0.00  0.0  0.0  0.00  0.00  0.00  ...   
max          2.0  2.00  2.00  2.00  2.00  2.0  2.0  2.00  2.00  2.00  ...   
pct_missing  0.2  0.32  0.36  0.36  0.18  0.3  0.3  0.28  0.32  0.28  ...   
first_NA     7.0  1.00  1.00  0.00  3.00  3.0  1.0  0.00  0.00  8.00  ...   

              40   41    42   43    44    45    46    47   48    49  
min          0.0  0.0  0.00  0.0  0.00  0.00  0.00  0.00  0.0  0.00  
max          2.0  2.0  2.00  2.0  2.00  2.00  2.00  2.00  2.0  2.00  
pct_missing  0.3  0.2  0.32  0.3  0.26  0.24  0.26  0.32  0.3  0.34  
first_NA     0.0  3.0  1.00  3.0  3.00  6.00  1.00  1.00  0.0  0.00  

[4 rows x 50 columns]


* Set a seed and then create a vector `v` consisting of a sample of 1,000 iid normal realizations with mean -10 and variance 100.

In [81]:
np.random.seed(1)

v = np.random.normal(loc = -10, scale = 10, size = 1000)

* Repeat this exercise by resetting the seed to ensure you obtain the same results. You can use the random module built in python or random.seed from numpy.

In [87]:
v = np.random.normal(loc = -10, scale = 10, size = 1000)

* Find the average of `v` and the standard error of `v`.

In [89]:
ave_v = np.mean(v)
sd_v = np.std(v)

print(f"Mean: {ave_v}, Std: {sd_v}")

Mean: -10.221685716021334, Std: 9.716231299281457


* Find the 5%ile of `v` and use the `norm` function from scipy.stats to compute what it theoretically should be. Is the estimate about what is expected by theory?

In [93]:
from scipy.stats import norm

real_ile = np.percentile(v, q = 5)
theo_ile = norm.ppf(q = 0.05, loc = -10, scale = 10)

print(f"Actual percentile: {real_ile}, theoretical percentile: {theo_ile}")

Actual percentile: -25.81653045935669, theoretical percentile: -26.44853626951473


* What is the percentile of `v` that corresponds to the value 0? What should it be theoretically? Is the estimate about what is expected by theory?

In [97]:
real_am = np.mean(v < 0)
theo_am = norm.cdf(x = 0, loc = -10, scale = 10)

print(f"Actual percentile: {real_am}, theoretical percentile: {theo_am}")

Actual percentile: 0.855, theoretical percentile: 0.8413447460685429


* Create a function `my_reverse` which takes as required input a vector `v` and returns the vector in reverse where the first entry is the last entry, etc. No function calls are allowed inside your function otherwise that would defeat the purpose of the exercise! (Yes, there is a base R function that does this called `rev`). 

In [137]:
def my_reverse(v: list):
    return v[::-1]

print(my_reverse(np.arange(0,50)))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


 * Built in methods in python to reverse a list.

In [135]:
#reverse using slicing
v = [1, 2, 3, 4, 5]
v_reversed = v[::-1]
print(v_reversed)

#using the .reverse method
v = [1, 2, 3, 4, 5]
v.reverse()
print(v)

[5, 4, 3, 2, 1]
[5, 4, 3, 2, 1]


* Create a function `flip_matrix` which takes as required input a matrix, an argument `dim_to_rev` that returns the matrix with the rows in reverse order or the columns in reverse order depending on the `dim_to_rev` argument. Let the default be the dimension of the matrix that is greater.

In [181]:
def flip_matrix(R):
    return np.flip(R, axis = 1)

print("1) \n", R)
print("2) \n", flip_matrix(R))

1) 
 [[ 0.  2.  1. ...  0. nan nan]
 [ 1. nan nan ... nan nan  0.]
 [ 1.  0.  0. ...  0. nan  0.]
 ...
 [ 2.  0.  2. ...  1.  0. nan]
 [ 1.  2. nan ... nan nan  1.]
 [ 0.  2.  2. ...  0. nan nan]]
2) 
 [[nan nan  0. ...  1.  2.  0.]
 [ 0. nan nan ... nan nan  1.]
 [ 0. nan  0. ...  0.  0.  1.]
 ...
 [nan  0.  1. ...  2.  0.  2.]
 [ 1. nan nan ... nan  2.  1.]
 [nan nan  0. ...  2.  2.  0.]]


* Create a list named `my_list` with keys "A", "B", ... where the entries are arrays of size 1, 2 x 2, 3 x 3 x 3, etc. Fill the array with the numbers 1, 2, 3, etc. Make 8 entries according to this sequence.

In [238]:
my_list = {chr(i + 64): np.full(np.repeat(i,i), fill_value = i) for i in range(1,9)}

print(my_list["C"])

[[[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]

 [[3 3 3]
  [3 3 3]
  [3 3 3]]]


* Run the following code:

In [240]:
import sys

sizes = {key: sys.getsizeof(value) for key, value in my_list.items()}


# Print the sizes
for key, size in sizes.items():
    print(f"Key: {key}, Size: {size} bytes")

Key: A, Size: 116 bytes
Key: B, Size: 144 bytes
Key: C, Size: 252 bytes
Key: D, Size: 1184 bytes
Key: E, Size: 12676 bytes
Key: F, Size: 186816 bytes
Key: G, Size: 3294380 bytes
Key: H, Size: 67109088 bytes


* Create vector `v` consisting of all numbers from -100 to 100 and test using the second line of code

In [244]:
v = np.arange(-100,101)
print(v)

[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90  -89  -88  -87
  -86  -85  -84  -83  -82  -81  -80  -79  -78  -77  -76  -75  -74  -73
  -72  -71  -70  -69  -68  -67  -66  -65  -64  -63  -62  -61  -60  -59
  -58  -57  -56  -55  -54  -53  -52  -51  -50  -49  -48  -47  -46  -45
  -44  -43  -42  -41  -40  -39  -38  -37  -36  -35  -34  -33  -32  -31
  -30  -29  -28  -27  -26  -25  -24  -23  -22  -21  -20  -19  -18  -17
  -16  -15  -14  -13  -12  -11  -10   -9   -8   -7   -6   -5   -4   -3
   -2   -1    0    1    2    3    4    5    6    7    8    9   10   11
   12   13   14   15   16   17   18   19   20   21   22   23   24   25
   26   27   28   29   30   31   32   33   34   35   36   37   38   39
   40   41   42   43   44   45   46   47   48   49   50   51   52   53
   54   55   56   57   58   59   60   61   62   63   64   65   66   67
   68   69   70   71   72   73   74   75   76   77   78   79   80   81
   82   83   84   85   86   87   88   89   90   91   92   93   94   95
   96 

* Test the `my_reverse` function using the following code:

In [246]:
# Test the function
v = list(range(1, 11))
v_reversed = my_reverse(v)
print(v)
print(v_reversed)
type(v_reversed)

assert my_reverse(v) == v[::-1], "my_reverse failed for numerical vector"

 # Test with character vector
v_char = ["A", "B", "C"]
assert my_reverse(v_char) == v_char[::-1], "my_reverse failed for character vector"

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [188]:
import re
import random

lorem = """Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Morbi posuere varius volutpat. Morbi faucibus ligula id massa ultricies viverra.
Donec vehicula sagittis nisi non semper. Donec at tempor erat.
Integer dapibus mi lectus, eu posuere arcu ultricies in.
Cras suscipit id nibh lacinia elementum. Curabitur est augue, congue eget quam in, scelerisque semper magna.
Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu. Mauris at sodales augue."""

t = re.split(pattern = "\n", string = lorem)
random.shuffle(t)
print(" ".join(t))


Donec vehicula sagittis nisi non semper. Donec at tempor erat. Morbi posuere varius volutpat. Morbi faucibus ligula id massa ultricies viverra. Cras suscipit id nibh lacinia elementum. Curabitur est augue, congue eget quam in, scelerisque semper magna. Aenean nulla ante, iaculis sed vehicula ac, finibus vel arcu. Mauris at sodales augue. Integer dapibus mi lectus, eu posuere arcu ultricies in. Lorem ipsum dolor sit amet, consectetur adipiscing elit.


* You have a set of names divided by gender (M / F) and generation (Boomer / GenX / Millenial):

M / Boomer      "Theodore, Bernard, Gene, Herbert, Ray, Tom, Lee, Alfred, Leroy, Eddie"

M / GenX        "Marc, Jamie, Greg, Darryl, Tim, Dean, Jon, Chris, Troy, Jeff"

M / Millennial  "Zachary, Dylan, Christian, Wesley, Seth, Austin, Gabriel, Evan, Casey, Luis"

F / Boomer      "Gloria, Joan, Dorothy, Shirley, Betty, Dianne, Kay, Marjorie, Lorraine, Mildred"

F / GenX        "Tracy, Dawn, Tina, Tammy, Melinda, Tamara, Tracey, Colleen, Sherri, Heidi"

F / Millennial  "Samantha, Alexis, Brittany, Lauren, Taylor, Bethany, Latoya, Candice, Brittney, Cheyenne"

Create python dictionary to store this data.


In [196]:
re.split(pattern = ", ", string = "Theodore, Bernard, Gene, Herbert, Ray, Tom, Lee, Alfred, Leroy, Eddie")

names = {"M": {"Boomer": re.split(pattern = ", ", string = "Theodore, Bernard, Gene, Herbert, Ray, Tom, Lee, Alfred, Leroy, Eddie"),
              "GenX" : re.split(pattern = ", ", string = "Marc, Jamie, Greg, Darryl, Tim, Dean, Jon, Chris, Troy, Jeff"),
              "Millennial": re.split(pattern = ", ", string = "Zachary, Dylan, Christian, Wesley, Seth, Austin, Gabriel, Evan, Casey, Luis")}, 
         "F": {"Boomer": re.split(pattern = ", ", string = "Gloria, Joan, Dorothy, Shirley, Betty, Dianne, Kay, Marjorie, Lorraine, Mildred"),
              "GenX" : re.split(pattern = ", ", string = "Tracy, Dawn, Tina, Tammy, Melinda, Tamara, Tracey, Colleen, Sherri, Heidi"),
              "Millennial": re.split(pattern = ", ", string = "Samantha, Alexis, Brittany, Lauren, Taylor, Bethany, Latoya, Candice, Brittney, Cheyenne")}}

print(names)
import pandas as pd

{'M': {'Boomer': ['Theodore', 'Bernard', 'Gene', 'Herbert', 'Ray', 'Tom', 'Lee', 'Alfred', 'Leroy', 'Eddie'], 'GenX': ['Marc', 'Jamie', 'Greg', 'Darryl', 'Tim', 'Dean', 'Jon', 'Chris', 'Troy', 'Jeff'], 'Millennial': ['Zachary', 'Dylan', 'Christian', 'Wesley', 'Seth', 'Austin', 'Gabriel', 'Evan', 'Casey', 'Luis']}, 'F': {'Boomer': ['Gloria', 'Joan', 'Dorothy', 'Shirley', 'Betty', 'Dianne', 'Kay', 'Marjorie', 'Lorraine', 'Mildred'], 'GenX': ['Tracy', 'Dawn', 'Tina', 'Tammy', 'Melinda', 'Tamara', 'Tracey', 'Colleen', 'Sherri', 'Heidi'], 'Millennial': ['Samantha', 'Alexis', 'Brittany', 'Lauren', 'Taylor', 'Bethany', 'Latoya', 'Candice', 'Brittney', 'Cheyenne']}}


* Now cleanup the namespace by deleting all stored objects and functions:

In [204]:
for name in dir():
    del globals()[name]

del globals()["name"]
print(dir())


['__builtins__']
